apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-service
  template:
    metadata:
      labels:
        app: ecommerce-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: ecommerce-service
          image: gcr.io/my-application-462106/ecommerce-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
            - secretRef:
                name: oidc-secrets    
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
