apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_NAME: ecommerce
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "25"
  DB_CONN_MAX_LIFETIME: 5m
